services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: rhc-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
