import type { SessionMemory, UiMessage } from "@rhc/types";

export type SessionReportInput = {
	sessionId: string;
	memory: SessionMemory;
	uiMessages: UiMessage[];
	generatedBy?: string;
};

export type SessionReport = {
	sessionId: string;
	generatedAt: string;
	markdown: string;
};

function listOrNone(items: string[]) {
	return items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : "- none";
}

export function buildSessionReport(input: SessionReportInput): SessionReport {
	const generatedAt = new Date().toISOString();
	const transcriptPreview = input.uiMessages
		.slice(-10)
		.map((message) => `- [${message.role}] ${message.content}`)
		.join("\n");

	const markdown = [
		`# Session Report: ${input.sessionId}`,
		"",
		`Generated at: ${generatedAt}`,
		`Generated by: ${input.generatedBy ?? "system"}`,
		"",
		"## Current Illness",
		input.memory.currentIllness ?? "Not set",
		"",
		"## Past Illnesses",
		listOrNone(input.memory.pastIllnesses),
		"",
		"## Risk Flags",
		listOrNone(input.memory.riskFlags),
		"",
		"## Recent Transcript",
		transcriptPreview.length > 0 ? transcriptPreview : "- no messages"
	].join("\n");

	return {
		sessionId: input.sessionId,
		generatedAt,
		markdown
	};
}
